version: 2.1
working_directory: ~/repo
jobs:
  build:
    docker:
      - image: cypress/base:10
      - image: circleci/node:11.10.1
    parallelism: 2
    steps:
      - checkout
      - restore_cache:
          keys:
            - cache-{{ .Branch }}-{{ checksum "package.json" }}
      - save_cache:
          key: cache-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - attach_workspace:
          at: ~/
      - run:
          name: Install packages
          command: npm install
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          name: Build app
          command: npm run build
      - run:
          name: Run e2e tests with Cypress
          command: npm run test:e2e:ci
      - run:
          name: Run unit tests with JUnit and default as reporter
          command: |
            ./cc-test-reporter before-build
            yarn test:unit --coverage
            ./cc-test-reporter after-build --coverage-input-type lcov --exit-code $?
      - run:
          name: Run unit tests with JUnit as reporter
          command: npm run test:unit:ci
          environment:
            JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"
      - store_test_results:
          path: "reports/junit"
