version: 2.1
working_directory: ~/repo
jobs:
  build:
    docker:
      - image: cypress/base:10
      - image: circleci/node:11.10.1
      parallelism: 2
    steps:
      - checkout
      - restore_cache:
          keys: cache-{{ .Branch }}-{{ checksum "package.json" }}
      - attach_workspace:
          at: ~/
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: cache-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - run:
          name: Build app
          command: npm run build

  test:
    docker:
      - image: cypress/base:10
      - image: circleci/node:11.10.1
    steps:
      - checkout
      - run:
        name: Run e2e tests with Cypress
        command: npm run test:e2e:ci
      - run:
        name: Run unit tests with JUnit as reporter
        command: npm run jest:junit
        environment:
          JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"
      - store_test_results:
        path: "reports/junit"

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
      - test:
        requires:
          - build
