# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
working_directory: ~/repo
jobs:
  build:
    docker:
    - image: cypress/base:10
    parallelism: 2
    steps:
    - checkout
    - restore_cache:
        keys:
        - cache-{{ .Branch }}-{{ checksum "package.json" }}
    - save_cache:
        key: cache-{{ .Branch }}-{{ checksum "package.json" }}
        paths:
        - ~/.npm
        - ~/.cache
    - attach_workspace:
        at: ~/
    - run:
        name: Install packages
        command: npm install
    - run:
        name: Build app
        command: npm run build
    - run:
        name: Run Cypress tests
        command: npm run test:e2e:ci
